[theme]
theme = "dracula" # Tema que combina com as cores que vocÃª estava usando

[icons]
icons = "material" # Requer font-awesome instalado

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = "Disk: $available"
interval = 20

[[block]]
block = "memory"
format = " $mem_used.eng(prefix:Mi)/$mem_total.eng(prefix:Mi)($mem_used_percents.eng(w:2)) "
format_alt = " MEMORY LOW: $mem_free "
interval = 5
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
format = " CPU: $utilization "
interval = 5

# Bloco de GPU 
[[block]]
block = "nvidia_gpu"
format = " GPU: $utilization/$temperature"
interval = 5

[[block]]
block = "net"
device = "enp7s0" # Verifique o nome da sua interface com 'ip link'
format = " ED: $graph_down($speed_down) "
format_alt = " EU: $graph_up($speed_up) "
interval = 5

[[block]]
block = "time"
#format_alt = " $timestamp.datetime(f:'%R', l:pt_BR) "
interval = 1
[block.format]
full = " $timestamp.datetime(f:'%a %d-%m-%Y %R:%S', l:pt_BR) "
short = " $timestamp.datetime(f:%R) "

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "weather"
autolocate = true
format = " $weather ($location) $temp "
[block.service]
name = "metno"
#lang = "pt"

[[block]]
block = "menu"
text = " \uf011  "
[[block.items]]
display = " -&gt;   Sleep   &lt;-"
cmd = "systemctl suspend"
[[block.items]]
display = " -&gt; Power Off &lt;-"
cmd = "poweroff"
confirm_msg = "Are you sure you want to power off?"
[[block.items]]
display = " -&gt;  Reboot   &lt;-"
cmd = "reboot"
confirm_msg = "Are you sure you want to reboot?"
